### ISSUE TITLE
Discontinuity of forces between pockets c and d

### ISSUE THREAD

**Issue by sebdenis** [ibell/pdsim#32]
Hi,

in `D1_forces` and `D2_forces` defined in symm_scroll_geo.pyx, there is a test to ensure the continuity with `C1_forces` and `C2_forces` :
```
if abs(theta-theta_d(geo))<1e-8:
     return C1_forces(theta,Nc,geo,poly)
```
Doing this way, it forces the continuity between pockets d1/c1.Nc and d2/c2.Nc. However, I think it should be done between d1/c1.Ncmax and d2/c2.Ncmax.

**Comment by ibell** [comment]
I think you are right.  I remember always seeing some funky spikes that I could never figure out where they came from.  I suspect you are onto it.  I'll have to do some testing to figure out whether this is indeed the problem, but it seems likely you have nailed it.
