### ISSUE TITLE
Scroll: sum of spinning moments not zero with ArcLineArc

### ISSUE THREAD

**Issue by ibell** [ibell/pdsim#67]
Failing test here: https://github.com/ibell/pdsim/commit/be2565fa08d730ef8b94fab163525bdfb2b786c2

**Comment by huges84** [comment]
Does this mean that ArcLineArc should not be used? Does 2Arc pass this test?

**Comment by ibell** [comment]
2Arc is fine, it is only the ArcLineArc that has the problem.  Thanks for the reminder to look back into this subtle point.
