### ISSUE TITLE
PDSim GUI failed to use REFPROP fluid

### ISSUE THREAD

**Issue by Wang-Zongwei** [ibell/pdsim#79]
Today I installed pdsim on a new PC (windows 11) with latest github code. I found below issue, and I hope my feedback is useful and not too elementary. 

1. Installation process is very smooth except below:
	ModuleNotFoundError: No module named 'pandas'

	This issue is easy to solve, only need input "pip install pandas", then it's OK.

2. PDSim GUI failed to use REFPROP fluid:
	The lastest version (PDSim 2.14 and CoolProp 6.5.0) cannot call REFPROP fluid in GUI. But the 2.9H windows setup version (downloaded from https://sourceforge.net/projects/pdsim/files/) seems OK to call the REFPROP fluid in GUI. Attached is related picture. (1st pic is based on PDSim GUI 2.14; 2nd pic is based on PDSim 2.9)

	Please help check if this issue could be fixed? Thanks very much.

![NOK](https://github.com/ibell/pdsim/assets/112040078/97cdb73c-914f-46a9-9a3a-ca07daac04ca)
![OK](https://github.com/ibell/pdsim/assets/112040078/e60ba73d-b36f-47bc-b526-200c49f6f26d)

**Comment by ibell** [comment]
How about REFPROP use without Bicubic interpolation, is that still ok?

**Comment by Wang-Zongwei** [comment]
> How about REFPROP use without Bicubic interpolation, is that still ok?

**Comment by ibell** [comment]
What error do you get?

**Comment by Wang-Zongwei** [comment]
For 2.14 conda GUI version, with o.r without Bicubic both NOK to call REFPROP. There is no any response if I select the "+" fluid:
BICUBIC&REFPROP::R32[0.697614699375863]&R125[0.302385300624138] or
REFPROP::R32[0.697614699375863]&R125[0.302385300624138] or
![part 1](https://github.com/ibell/pdsim/assets/112040078/29606220-6026-4d23-a393-1882e72fdad5)
![part 2](https://github.com/ibell/pdsim/assets/112040078/45054515-3405-49d3-88da-c0084754d688)

**Comment by ibell** [comment]
Fixed, there was an error message in the main output log

**Comment by Wang-Zongwei** [comment]
Thanks so much.

**Comment by Wang-Zongwei** [comment]
I found latest verison from "/pdsim/tree/HEOSGUI" already solved this issue. Thanks so much!!!
