### ISSUE TITLE
Different discharge port diameter but exactly same performance result

### ISSUE THREAD

**Issue by Wang-Zongwei** [ibell/pdsim#80]
I want to study with PDSim GUI the impact of different discharge port diameter on scroll compressor performance. But I found it seems no performance change (volumetric and isentropic efficiency) under different discharge port diameter input.

GUI version: PDSim 2.14 and CoolProp 6.5.0
All scroll input parameter keeps same as default setting value except discharge port diameter.

Do you think such result is reasonable? Thanks very much.
![Dis port](https://github.com/ibell/pdsim/assets/112040078/f35c2e16-a626-492f-9c27-8659c4434d29)

**Comment by ibell** [comment]
Are the coordinates of the port the same? You might want to put in the port
coordinates yourself

**Comment by Wang-Zongwei** [comment]
I did't input any coordinates for the discharge port (all x,y keeps blank). I will try with different coordinates input data to see if the performance result is different.

**Comment by Wang-Zongwei** [comment]
I have got reasonable performance result with different coordinates input data for discharge port (see pic).
I will use this method for my future study.
![xy](https://github.com/ibell/pdsim/assets/112040078/45414fed-d0b3-4599-90d3-f0adbcbc1ace)

**Comment by Wang-Zongwei** [comment]
Thanks for your help.
