### ISSUE TITLE
Valve Modelling

### ISSUE THREAD

**Issue by tomam28** [ibell/pdsim#86]
https://github.com/ibell/pdsim/blame/710b8615a7d9dd67afff9c8d1bf608a9eb97efe8/examples/scroll_compressor_valves.py#L152

Hello Dr. Bell,

from where is the valve stiffness equation. Do you consider a fixed end beam because the Moment of inertia is a beam? The other values for the valve are clear.

Thanks a lot! :)

**Comment by ibell** [comment]
You figure it out?

**Comment by tomam28** [comment]
Yes you assumed a force not at the end of the beam, but at the length a. And I found the corresponding formula in [Source](https://asmedigitalcollection.asme.org/dynamicsystems/article/142/11/111001/1084330/Modeling-and-Experimental-Validation-of-a-Reed) p.73.
